Program ini saya buat untuk mengikuti kompetisi ML pada situs kaggle.com, program ini bertujuan untuk memprediksi harga rumah dengan menggunakan Machine Learning model.

Import 2 dataset, yaitu dataset test dan train 

In [ ]:
import pandas as pd

df_test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Housing Price Model/test.csv')
df_train = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Housing Price Model/train.csv')

memilih kolom yang akan dijadikan sebagai feature

In [ ]:
df_train = df_train[['LotArea', 'OverallQual', 'OverallCond', 'YearBuilt','YearRemodAdd', 'TotalBsmtSF', 'GrLivArea', 'TotRmsAbvGrd', 'BedroomAbvGr', 'FullBath'
           , 'BsmtFinSF1', 'Fireplaces', 'GarageArea', 'GarageCars', 'PoolArea', 'MiscVal', 'YrSold'
           , 'Neighborhood', 'SaleType', 'SaleCondition','SalePrice']] 

In [ ]:
df_train.shape

(1460, 21)

memilih kolom yang akan dijadikan feature pada dataset test

In [ ]:
df_test = df_test[['LotArea', 'OverallQual', 'OverallCond', 'YearBuilt','YearRemodAdd', 'TotalBsmtSF', 'GrLivArea', 'TotRmsAbvGrd', 'BedroomAbvGr', 'FullBath'
           , 'BsmtFinSF1', 'Fireplaces', 'GarageArea', 'GarageCars', 'PoolArea', 'MiscVal', 'YrSold'
           , 'Neighborhood', 'SaleType', 'SaleCondition']] 

In [ ]:
df_test.shape

(1459, 20)

menangani missing value dengan agregasi mean

In [ ]:
#mengisi missing value di data test
df_test = df_test.fillna(value = {'TotalBsmtSF': df_test['TotalBsmtSF'].mean(), 'BsmtFinSF1': df_test['BsmtFinSF1'].mean(),
                         'GarageArea': df_test['GarageArea'].mean(), 
                         'GarageCars': df_test['GarageCars'].mean(),
                         'SaleType' :'WD'})

melakukan encoding untuk merubah data katagorikal menjadi data numerik

In [ ]:
#melakukan encoding untuk data katagorikal

import numpy as np
from sklearn.preprocessing import LabelEncoder

LE = LabelEncoder()
df_train['Neighborhood'] = LE.fit_transform(df_train['Neighborhood'])
print(LE.classes_)
print(np.sort(df_train['Neighborhood'].unique()))
print('==================================================================')

LE = LabelEncoder()
df_train['SaleType'] = LE.fit_transform(df_train['SaleType'])
print(LE.classes_)
print(np.sort(df_train['SaleType'].unique()))
print('==================================================================')

LE = LabelEncoder()
df_train['SaleCondition'] = LE.fit_transform(df_train['SaleCondition'])
print(LE.classes_)
print(np.sort(df_train['SaleCondition'].unique()))
print('==================================================================')

['Blmngtn' 'Blueste' 'BrDale' 'BrkSide' 'ClearCr' 'CollgCr' 'Crawfor'
 'Edwards' 'Gilbert' 'IDOTRR' 'MeadowV' 'Mitchel' 'NAmes' 'NPkVill'
 'NWAmes' 'NoRidge' 'NridgHt' 'OldTown' 'SWISU' 'Sawyer' 'SawyerW'
 'Somerst' 'StoneBr' 'Timber' 'Veenker']
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
['COD' 'CWD' 'Con' 'ConLD' 'ConLI' 'ConLw' 'New' 'Oth' 'WD']
[0 1 2 3 4 5 6 7 8]
['Abnorml' 'AdjLand' 'Alloca' 'Family' 'Normal' 'Partial']
[0 1 2 3 4 5]


In [ ]:
df_train.head()

LotArea  OverallQual  OverallCond  ...  SaleType  SaleCondition  SalePrice
0     8450            7            5  ...         8              4     208500
1     9600            6            8  ...         8              4     181500
2    11250            7            5  ...         8              4     223500
3     9550            7            5  ...         8              0     140000
4    14260            8            5  ...         8              4     250000

[5 rows x 21 columns]

In [ ]:
#melakukan encoding untuk data katagorikal

import numpy as np
from sklearn.preprocessing import LabelEncoder

LE = LabelEncoder()
df_test['Neighborhood'] = LE.fit_transform(df_test['Neighborhood'])
print(LE.classes_)
print(np.sort(df_test['Neighborhood'].unique()))
print('==================================================================')

LE = LabelEncoder()
df_test['SaleType'] = LE.fit_transform(df_test['SaleType'])
print(LE.classes_)
print(np.sort(df_test['SaleType'].unique()))
print('==================================================================')

LE = LabelEncoder()
df_test['SaleCondition'] = LE.fit_transform(df_test['SaleCondition'])
print(LE.classes_)
print(np.sort(df_test['SaleCondition'].unique()))
print('==================================================================')

['Blmngtn' 'Blueste' 'BrDale' 'BrkSide' 'ClearCr' 'CollgCr' 'Crawfor'
 'Edwards' 'Gilbert' 'IDOTRR' 'MeadowV' 'Mitchel' 'NAmes' 'NPkVill'
 'NWAmes' 'NoRidge' 'NridgHt' 'OldTown' 'SWISU' 'Sawyer' 'SawyerW'
 'Somerst' 'StoneBr' 'Timber' 'Veenker']
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
['COD' 'CWD' 'Con' 'ConLD' 'ConLI' 'ConLw' 'New' 'Oth' 'WD']
[0 1 2 3 4 5 6 7 8]
['Abnorml' 'AdjLand' 'Alloca' 'Family' 'Normal' 'Partial']
[0 1 2 3 4 5]


In [ ]:
df_test.head()

LotArea  OverallQual  OverallCond  ...  Neighborhood  SaleType  SaleCondition
0    11622            5            6  ...            12         8              4
1    14267            6            6  ...            12         8              4
2    13830            5            5  ...             8         8              4
3     9978            6            6  ...             8         8              4
4     5005            8            5  ...            22         8              4

[5 rows x 20 columns]

In [ ]:
df_train.corr().style.background_gradient().set_precision(2)

In [ ]:
X = df_train.drop(['SalePrice'], axis = 1)
y = df_train['SalePrice']
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (1460, 20)
Shape of y: (1460,)


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X, y, train_size=0.8, test_size=0.2, random_state = 0)

In [ ]:
from xgboost import XGBRegressor

model = XGBRegressor(n_estimators = 10000, learning_rate = 0.095)
model.fit(X_train, y_train,
          early_stopping_rounds = 55, 
          eval_set = [(X_valid, y_valid)], 
          verbose = False)

[10:28:06] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.095, max_delta_step=0,
             max_depth=3, min_child_weight=1, missing=None, n_estimators=10000,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [ ]:
from sklearn.metrics import mean_absolute_error

val_predictions = model.predict(X_valid)
val_mae = mean_absolute_error(val_predictions, y_valid)
print('MAE adalah : ',val_mae)

MAE adalah :  15479.57511504709


In [ ]:
model.fit( df_train.drop(['SalePrice'], axis = 1), df_train['SalePrice'],
          early_stopping_rounds = 55, 
          eval_set = [(X_valid, y_valid)], 
          verbose = False)

test_preds = model.predict(df_test)

[11:23:57] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


In [ ]:
test_preds.shape

(1459,)

In [ ]:
output = pd.DataFrame({'Id': pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Housing Price Model/test.csv').Id,
                       'SalePrice': test_preds})
output.to_csv('submission.csv', index=False)

In [ ]:
hasil = pd.read_csv('/content/submission.csv')
hasil.head()

Id  SalePrice
0  1461  141275.25
1  1462  144826.60
2  1463  193342.94
3  1464  200495.70
4  1465  192722.84